### ISSUE TITLE
Remove identity

### ISSUE THREAD

**Issue by mivano** [GlobalDevOpsBootcamp/eShopOnWeb#12]
Remove the identity system so it is not in its way.

**Comment by mibo32** [comment]
@mivano  @rajbos  @ovebastiansen  removing the identity => we kill the admin page and the orders page
Is this what we want ?

**Comment by mivano** [comment]
Main purpose is to make it a clean and lean system. So no use of a SQL server (as that is harder to roll out at scale due to limitations). As the membership/users depend on the database as well and as we do not have anything specific regarding auth, we rather remove it. So a simple static user/pass is enough, all the other stuff is not needed.

**Comment by mibo32** [comment]
@mivano Can you check the pr ? we removed it completely

**Comment by mivano** [comment]
@rajbos you looked at this code before, can you have a look?
