### ISSUE TITLE
Tag the `eShopOnWeb` team on the creation of an issue

### ISSUE THREAD

**Issue by rajbos** [GlobalDevOpsBootcamp/eShopOnWeb#25]
No one is handling the issuesi in this repo. Since we clone this to every team, it would be nice if it is up to date. To alert the right folks, add a workflow file that creates a comment with the team name to trigger a notification.

Use [devops-actions/issue-comment-tag](https://github.com/devops-actions/issue-comment-tag) action to tag the `eShopOnWeb` team.

**Comment by rajbos** [comment]
After adding this workflow, we should remove the file when we clone it in the `challenge-builder` repo.

**Comment by madkoo** [comment]
@rajbos  there is no eShopOnWeb team? or am I misunderstanding what is needed to be done?

**Comment by rajbos** [comment]
Good point. We already add the issues to the project, so this is no longer needed. Closing this one!
