### ISSUE TITLE
Add dependabot setup to prevent the updates to packages on .NET 6.0

### ISSUE THREAD

**Issue by rajbos** [GlobalDevOpsBootcamp/eShopOnWeb#34]
As @wulfland noticed yesterday: the open PR's that fail from dependabots setup seem to come from the fact that dependabot blindly updates all available NuGet packages to the latest version, without checking if they would work with the target framework version (which is 5). 

- [ ] Add dependabot configuration file to prevent updates to mayor versions

**Comment by ovebastiansen** [comment]
why are we not upgrading to net6? and should we integrate the 41 commits that happen on upstream?

**Comment by rajbos** [comment]
Let's **not** pull in the upstream changes! We are adding new stuff here that we need (In fact, we should break the fork). Not sure on .NET 6 either or what it would bring for us. If you feel the need, create a branch and test things out. Do note: I don't think the GitHub runners already have 6 installed out of the box. Not sure on Azure Web Apps.

**Comment by ovebastiansen** [comment]
net5 has end of support on 8.may, just before the event ;), so just to make sure we doesn't look bad, I will try to upgrade to 6 in a branch then to test things out

**Comment by MagnusTim** [comment]
DotNet 6 is installed on the Windows GH hosted runners
https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md
