### ISSUE TITLE
Convert eShopOnWeb images / style to Parts Unlimited

### ISSUE THREAD

**Issue by rajbos** [GlobalDevOpsBootcamp/eShopOnWeb#7]
Check Parts Unlimited repo from GDBC2019: [https://dev.azure.com/globaldevopsbootcamp/Challenges/_git/PartsUnlimited-Clean?path=/src/PartsUnlimitedWebsite/images](https://dev.azure.com/globaldevopsbootcamp/Challenges/_git/PartsUnlimited-Clean?path=/src/PartsUnlimitedWebsite/images) for images to reuse and styling options

**Comment by mericstam** [comment]
Not sure I am clever enough to do this.  Frontend stuff is not my field :)

**Comment by rajbos** [comment]
Me neither, but you can get us started, right? Overwrite the images is step 1 IMO 😁 .
