### ISSUE TITLE
Convert SQL to Azure Storage so we do not need a SQL database

### ISSUE THREAD

**Issue by mivano** [GlobalDevOpsBootcamp/eShopOnWeb#8]
In order to save on cost/time for rolling out SQL server, we want to make use of storage accounts instead. The number of data points can also be from memory, not everything need to be in the storage.

**Comment by rajbos** [comment]
Is there anything needed *at all* the comes from the database?

**Comment by mericstam** [comment]
It is already setup for in memory

**Comment by rajbos** [comment]
Can you check the deployment for a team then @mericstam ? I think that failed because of the missing connection string (I might be wrong then).

**Comment by rajbos** [comment]
Checked the deployment myself. Db not needed anymore
